export const techStackExp = [
  'JavaScript',
  'TypeScript',
  'Node.js',
  'Express',
  'Socket.io',
  'Sequelize',
  'Mongoose',
  'React.js',
  'Vue.js',
  'html',
  'css',
  'axios',
  'Jest',
  'MongoDB',
  'PostgreSQL',
  'Linux',
  'Git',
  'Docker',
  'AWS',
  'Service oriented architecture SOA',
  'MicroServices architecture',
  'Event driven architecture',
  'Test driven development',
  'REST API',
  'Web Sockets',
  'Linux-based environment',
];

export const infinityExp = [
  {
    title: 'Full Stack Developer - Dev core team',
    company: 'Infinity Labs R&D',
    period: '2024-2025',
    descriptions: [
      'Part of the core development team which is responsible for architectural decisions, defining company-wide development conventions, and developing the infrastructure of the application, which includes multiple microservices under its responsibility.',
      'Developed and maintained a micro-service for guest users invites management system.',
      "Created and managed npm packages to be used across the app's services.",
    ],
    techStack: [
      'JavaScript',
      'TypeScript',
      'Node.js',
      'Express',
      'Sequelize',
      'Mongoose',
      'React.js',
      'axios',
      'Jest',
      'npm packages',
      'MongoDB',
      'PostgreSQL',
      'Git',
      'Docker',
      'AWS',
      'MicroServices architecture',
      'Event driven architecture',
      'Test driven development',
      'REST API',
      'Linux-based environment',
    ],
  },

  {
    title: 'Full Stack Developer - Dashboard team',
    company: 'Infinity Labs R&D',
    period: '2022-2024',
    descriptions: [
      'Oversaw the entire development lifecycle of an educational Saas web application (SOA based) for students. Responsibilities included designing and implementing REST APIs, adding new features, and performing ongoing maintenance to improve functionality and user experience.',
      'Acted as the main software developer in the team, defining workflows, operational procedures, and guidelines for development, and served as the primary point of contact for support and technical questions from team members.',
      'Optimized system performance and improved response times by 80%.',
      'Refactored the backend by independently rewriting the code to extract the core framework.',
      'Mentored students in a software development extensive bootcamp, delivering comprehensive instruction in C programming, Java, OOP, Design Patterns, fundamental programming concepts, algorithms, software design, multithreading, and system programming, while focusing on core principles and best practices.',
    ],
    techStack: [
      'JavaScript',
      'TypeScript',
      'Node.js',
      'Express',
      'Socket.io',
      'Sequelize',
      'Vue.js',
      'html',
      'css',
      'axios',
      'Jest',
      'PostgreSQL',
      'Git',
      'Docker',
      'AWS',
      'Service oriented architecture SOA',
      'Object oriented programming',
      'MicroServices architecture',
      'Event driven architecture',
      'Test driven development',
      'REST API',
      'Web Sockets',
      'Linux-based environment',
    ],
  },
];
