export const techStackExp = [
  'JavaScript',
  'TypeScript',
  'Node.js',
  'Express',
  'Socket.io',
  'Sequelize',
  'Mongoose',
  'React.js',
  'Vue.js',
  'HTML',
  'CSS',
  'axios',
  'Jest',
  'MongoDB',
  'PostgreSQL',
  'Linux',
  'Git',
  'Docker',
  'AWS',
  'Service oriented architecture SOA',
  'MicroServices architecture',
  'Event driven architecture',
  'Test driven development',
  'REST API',
  'Web Sockets',
  'Linux-based environment',
];

export const workExp = [
  {
    title: 'Back End Developer',
    company: 'Pango',
    period: '2025 - present',
    descriptions: [
      'Domain owner of the EvCharge service, responsible for electric vehicle charging flows in a complex production environment combining both software and hardware-related challenges. Working with Python, MongoDB, AWS, Lambda, message queues- SQS and DLQ, SNS, SSM, Api gateways, CloudWatch, Coralogix, DynamoDB, serverless architecture, microservices, and nano-services architecture.',
      'Led the ongoing maintenance and evolution of the domain, including designing and implementing new features, resolving production issues, and supporting internal teams as well as external vendors.',
      'Led the architecture and development of an internal multi-agent bot designed to centralize and expose domain knowledge across the company. Owned the overall architecture and most of the implementation, defined the development patterns and guidelines used by other teams to build their specialist agents, and deployed the agents on AWS EKS and EC2. The agent ecosystem included in-house wrappers around Cursor CLI as well as native Cursor Agents.',
      'Actively AI-oriented in day-to-day development, leveraging Cursor and Claude Code, and creating internal skills, commands, roles, and agents to optimize workflows and share best practices across the team.',
      'Designed and implemented agentic development workflows using a fleet of specialized sub-agents to support the end-to-end implementation of new features in the EvCharge domain, from analysis and planning through development and validation.',
      'Delivered new features involving complex deployments across multiple microservices simultaneously, while ensuring system stability and continuity in production.',
      'Improved observability and incident response by implementing alerts and monitoring flows to detect bugs in real time and enable faster investigation and resolution.',
      'Developed a full-stack internal application using also Docker and React to create semi-automated processes, enabling non-technical stakeholders to perform domain-related operations independently.',
    ],
    techStack: [
      'Python',
      'DynamoDB',
      'MongoDB',
      'Redis',
      'AWS Lambda',
      'AWS SQS',
      'AWS SNS',
      'AWS EKS',
      'AWS EC2',
      'AWS APIGateway',
      'CloudWatch',
      'Agentic AI Development',
      'AWS',
      'MCP',
      'Microservices architecture',
      'Serverless architecture',
      'Event driven architecture',
      'Test driven development',
      'Object Oriented Programming',
      'Docker',
      'Git',
      'REST API',
    ],
  },
  {
    title: 'Full Stack Developer - Dev core team',
    company: 'Infinity Labs R&D',
    period: '2024 - 2025',
    descriptions: [
      'Part of the core development team which is responsible for architectural decisions, defining company-wide development conventions, and developing the infrastructure of the application, which includes multiple microservices under its responsibility.',
      'Developed and maintained a micro-service for guest users invites management system.',
      "Created and managed npm packages to be used across the app's services.",
    ],
    techStack: [
      'JavaScript',
      'TypeScript',
      'Node.js',
      'Express',
      'Sequelize',
      'Mongoose',
      'React.js',
      'Axios',
      'Jest',
      'Npm packages',
      'MongoDB',
      'PostgreSQL',
      'Git',
      'Docker',
      'AWS',
      'MicroServices architecture',
      'Event driven architecture',
      'Test driven development',
      'REST API',
      'Linux-based environment',
    ],
  },
  {
    title: 'Full Stack Developer - Dashboard team',
    company: 'Infinity Labs R&D',
    period: '2022 - 2024',
    descriptions: [
      'Oversaw the entire development lifecycle of an educational Saas web application (SOA based) for students. Responsibilities included designing and implementing REST APIs, adding new features, and performing ongoing maintenance to improve functionality and user experience.',
      'Acted as the main software developer in the team, defining workflows, operational procedures, and guidelines for development, and served as the primary point of contact for support and technical questions from team members.',
      'Optimized system performance and improved response times by 80%.',
      'Refactored the backend by independently rewriting the code to extract the core framework.',
      'Mentored students in a software development extensive bootcamp, delivering comprehensive instruction in C programming, Java, OOP, Design Patterns, fundamental programming concepts, algorithms, software design, multithreading, and system programming, while focusing on core principles and best practices.',
    ],
    techStack: [
      'JavaScript',
      'TypeScript',
      'Node.js',
      'Express',
      'Socket.io',
      'Sequelize',
      'Vue.js',
      'HTML',
      'CSS',
      'Axios',
      'Jest',
      'PostgreSQL',
      'Git',
      'Docker',
      'AWS',
      'Service oriented architecture SOA',
      'Object oriented programming',
      'MicroServices architecture',
      'Event driven architecture',
      'Test driven development',
      'REST API',
      'Web Sockets',
      'Linux-based environment',
    ],
  },
];
